(() => {
 const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
 const KEY='mesraah_v030';
 const seed={profile:{name:'',email:''},points:35,spaces:[{id:'personal',name:'شخصي'},{id:'work',name:'العمل'},{id:'family',name:'العائلة'}],people:[],rewards:[{id:'r1',name:'قهوة ومشوار',points:50},{id:'r2',name:'عشاء',points:100}],tasks:[]};
 let data=load(); let filter='all'; let pendingFly=null;
 function load(){try{return {...seed,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(seed)}}
 function save(){localStorage.setItem(KEY,JSON.stringify(data));renderAll()}
 function id(){return Math.random().toString(36).slice(2,9)}
 function today(){return new Date().toISOString().slice(0,10)}
 function addDays(date,n){const d=new Date(date+'T12:00:00');d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)}
 function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1700)}
 function esc(s=''){return s.replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
 function taskHTML(t){const sp=data.spaces.find(x=>x.id===t.spaceId);const pe=data.people.find(x=>x.id===t.personId);const late=t.due&&t.due<today()&&t.status!=='done';return `<article class="task-item" data-task="${t.id}"><button class="task-check" data-done="${t.id}" aria-label="إنجاز المهمة"></button><div><div class="task-title">${esc(t.title)}</div><div class="task-meta">${sp?`<span class="chip">${esc(sp.name)}</span>`:''}${pe?`<span class="chip">${esc(pe.name)}</span>`:''}${t.due?`<span class="chip ${late?'red':''}">${t.due}</span>`:''}${t.status==='waiting'?'<span class="chip gold">انتظار</span>':''}</div></div><button class="task-more" data-edit="${t.id}">•••</button></article>`}
 function activeTasks(){return data.tasks.filter(t=>t.status!=='done')}
 function renderAll(){renderSpaces();renderToday();renderInbox();renderPeople();renderFollowups();renderAchievements();renderRewards();renderManage();fillSelects()}
 function renderSpaces(){const html=data.spaces.map(s=>`<button class="space-link" data-space="${s.id}">${esc(s.name)}</button>`).join('');$('#sidebarSpaces').innerHTML=html;$('#spaceGrid').innerHTML=data.spaces.map(s=>{const n=activeTasks().filter(t=>t.spaceId===s.id).length;return `<article class="space-card"><h3>${esc(s.name)}</h3><p>${n} مهمة مفتوحة</p></article>`}).join('')}
 function renderToday(){const tasks=activeTasks().filter(t=>t.due===today()||(!t.due&&t.status==='active'));const shown=tasks.filter(t=>filter==='all'||(filter==='important'&&['important','strategic'].includes(t.priority))||(filter==='waiting'&&t.status==='waiting'));$('#todayTaskList').innerHTML=shown.map(taskHTML).join('');$('#todayEmpty').hidden=shown.length>0;const done=data.tasks.filter(t=>t.status==='done'&&t.completedAt?.slice(0,10)===today()).length;const late=activeTasks().filter(t=>t.due&&t.due<today()).length;const waiting=activeTasks().filter(t=>t.status==='waiting').length;$('#statToday').textContent=tasks.length;$('#statLate').textContent=late;$('#statWaiting').textContent=waiting;$('#statDone').textContent=done;$('#todayNavCount').textContent=tasks.length;$('#followNavCount').textContent=waiting;const pct=tasks.length+done?Math.round(done/(tasks.length+done)*100):0;$('#dayProgress').textContent=pct+'%';$('.day-ring').style.setProperty('--progress',pct+'%');$('#pointsBalance').textContent=data.points;const focus=[...activeTasks()].sort((a,b)=>(b.priority==='strategic')-(a.priority==='strategic')||(a.due||'9999').localeCompare(b.due||'9999'))[0];$('#focusTask').innerHTML=focus?`<div class="focus-box"><h3>${esc(focus.title)}</h3><p>${focus.due?'موعدها '+focus.due:'بدون موعد محدد'}</p></div>`:'<div class="focus-box"><h3>ما عندك مهمة مختارة</h3><p>أضف مهمة وراح تظهر هنا.</p></div>';const wr=activeTasks().filter(t=>t.status==='waiting').slice(0,6);$('#waitingList').innerHTML=wr.map(t=>`<article class="waiting-card"><h3>${esc(t.title)}</h3><p>${t.follow?'متابعة '+t.follow:'بانتظار رد'}</p></article>`).join('')||'<article class="waiting-card"><h3>ما فيه شيء معلق</h3><p>ممتاز.</p></article>';renderNextReward()}
 function renderNextReward(){const next=[...data.rewards].filter(r=>r.points>data.points).sort((a,b)=>a.points-b.points)[0];if(next){const pct=Math.min(100,Math.round(data.points/next.points*100));$('#pointsTrack').style.width=pct+'%';$('#nextReward').innerHTML=`<div class="reward-next">باقي ${next.points-data.points} نقطة إلى ${esc(next.name)}</div>`}else{$('#pointsTrack').style.width='100%';$('#nextReward').innerHTML='<div class="reward-next">عندك رصيد لمكافأة.</div>'}}
 function renderInbox(){const arr=activeTasks().filter(t=>t.status==='inbox');$('#inboxList').innerHTML=arr.map(taskHTML).join('');$('#inboxEmpty').hidden=arr.length>0;$('#inboxNavCount').textContent=arr.length}
 function renderPeople(){const counts=p=>activeTasks().filter(t=>t.personId===p.id).length;$('#peopleGrid').innerHTML=data.people.map(p=>`<article class="person-card"><h3>${esc(p.name)}</h3><p>${counts(p)} مهمة مرتبطة</p></article>`).join('')||'<article class="person-card"><h3>أضف أول شخص</h3><p>تظهر تحته كل المهام والمتابعات.</p></article>'}
 function renderFollowups(){const arr=activeTasks().filter(t=>t.follow||t.status==='waiting').sort((a,b)=>(a.follow||'9999').localeCompare(b.follow||'9999'));$('#followupList').innerHTML=arr.map(taskHTML).join('')||'<div class="empty-state"><span>↻</span><h3>ما فيه متابعة</h3></div>'}
 function renderAchievements(){const done=data.tasks.filter(t=>t.status==='done');const now=new Date();const weekStart=new Date(now);weekStart.setDate(now.getDate()-6);$('#achToday').textContent=done.filter(t=>t.completedAt?.slice(0,10)===today()).length;$('#achWeek').textContent=done.filter(t=>t.completedAt&&new Date(t.completedAt)>=weekStart).length;$('#achAll').textContent=done.length;$('#achPoints').textContent=done.reduce((s,t)=>s+(t.points||0),0);$('#achievementList').innerHTML=done.slice().reverse().map(t=>`<article class="task-item"><span>✓</span><div><div class="task-title">${esc(t.title)}</div><div class="task-meta"><span class="chip gold">+${t.points||0} نقطة</span></div></div></article>`).join('')||'<div class="empty-state"><h3>أول إنجاز يبدأ من أول مهمة.</h3></div>'}
 function renderRewards(){$('#rewardBalance').textContent=data.points;$('#rewardGrid').innerHTML=data.rewards.map(r=>`<article class="reward-card"><h3>${esc(r.name)}</h3><p>${r.points} نقطة</p><button class="secondary-btn" data-redeem="${r.id}" ${data.points<r.points?'disabled':''}>استخدم</button></article>`).join('')}
 function renderManage(){
  data.profile=data.profile||{name:'',email:''};
  $('#profileName').value=data.profile.name||'';
  $('#profileEmail').value=data.profile.email||'';
  $('#manageSpacesCount').textContent=data.spaces.length+' جهة أو مساحة';
  $('#managePeopleCount').textContent=data.people.length+' شخص';
  $('#manageRewardsCount').textContent=data.rewards.length+' مكافأة';
  const ready=Boolean(data.profile.name);
  $('#manageStatus').textContent=ready?'تم إعداد الحساب':'الإعداد الأول';
  $('#setupNudge').hidden=ready;
  $('#sidebarUserName').textContent=ready?data.profile.name:'إعداد الحساب';
  $('#sidebarUserAvatar').textContent=ready?(data.profile.name.trim().charAt(0)||'م'):'م';
  const h=new Date().getHours();
  $('#greeting').textContent=ready?((h<12?'صباح الخير':'مساء الخير')+' يا '+data.profile.name):'أهلًا بك في مِسراح';
 }
 function fillSelects(){const sp='<option value="">بدون مساحة</option>'+data.spaces.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('');const pe='<option value="">بدون شخص</option>'+data.people.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');$('#taskSpace').innerHTML=sp;$('#taskPerson').innerHTML=pe}
 function openTask(t=null){$('#taskForm').reset();$('#taskId').value=t?.id||'';$('#taskModalTitle').textContent=t?'تعديل المهمة':'مهمة جديدة';$('#deleteTaskBtn').hidden=!t;if(t){$('#taskTitle').value=t.title||'';$('#taskNotes').value=t.notes||'';$('#taskSpace').value=t.spaceId||'';$('#taskPerson').value=t.personId||'';$('#taskStatus').value=t.status||'inbox';$('#taskPriority').value=t.priority||'normal';$('#taskDue').value=t.due||'';$('#taskFollow').value=t.follow||'';$('#taskPoints').value=t.points||10}$('#taskModal').showModal()}
 function parseFly(text){text=text.trim();let due='',follow='',spaceId='',personId='';const td=today();if(/بكره|بكرة|غد/.test(text)) due=addDays(td,1);else if(/اليوم/.test(text)) due=td;const days={'الأحد':0,'الاحد':0,'الاثنين':1,'الثلاثاء':2,'الأربعاء':3,'الاربعاء':3,'الخميس':4,'الجمعة':5,'السبت':6};for(const [name,idx] of Object.entries(days)){if(text.includes(name)){const d=new Date();const delta=(idx-d.getDay()+7)%7||7;due=addDays(td,delta);break}}const fm=text.match(/بعد\s+(\d+)\s+يوم/);if(fm) follow=addDays(due||td,Number(fm[1]));for(const s of data.spaces){if(text.includes(s.name)){spaceId=s.id;break}}for(const p of data.people){if(text.includes(p.name)){personId=p.id;break}}let title=text.replace(/(?:اليوم|بكره|بكرة|غدًا|غدا)/g,'').replace(/بعد\s+\d+\s+يوم(?:ين)?/g,'').replace(/\s+/g,' ').trim();return {title,due,follow,spaceId,personId,status:'inbox',priority:/مهم|عاجل/.test(text)?'important':'normal',points:10,notes:'',createdAt:new Date().toISOString()}}
 function showFlyPreview(t){pendingFly=t;const sp=data.spaces.find(s=>s.id===t.spaceId);const pe=data.people.find(p=>p.id===t.personId);$('#flyPreview').innerHTML=`<strong>${esc(t.title)}</strong><small>${[sp?.name,pe?.name,t.due&&'الموعد '+t.due,t.follow&&'المتابعة '+t.follow].filter(Boolean).join(' • ')||'ستدخل إلى الوارد'}</small><div class="fly-actions"><button class="fly-save" id="flySave">حفظ</button><button class="fly-edit" id="flyEdit">تعديل</button></div>`;$('#flyPreview').classList.add('show')}
 function initFly(){const btn=$('#flyVoice'),input=$('#flyInput'),send=$('#flySend');const go=()=>{if(!input.value.trim())return;showFlyPreview(parseFly(input.value))};send.onclick=go;input.addEventListener('keydown',e=>{if(e.key==='Enter')go()});const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){btn.onclick=()=>{input.focus();toast('الإدخال الصوتي يحتاج متصفح يدعم المايك')} ;return}btn.onclick=()=>{const r=new SR();r.lang='ar-SA';r.interimResults=false;btn.classList.add('listening');r.start();r.onresult=e=>{input.value=e.results[0][0].transcript;showFlyPreview(parseFly(input.value))};r.onend=()=>btn.classList.remove('listening');r.onerror=()=>{btn.classList.remove('listening');toast('تعذر تشغيل المايك')}}}
 document.addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav){$$('.nav-item').forEach(x=>x.classList.remove('active'));nav.classList.add('active');showView(nav.dataset.view)}const open=e.target.closest('[data-open-view]');if(open)showView(open.dataset.openView);const done=e.target.closest('[data-done]');if(done){const t=data.tasks.find(x=>x.id===done.dataset.done);if(t){t.status='done';t.completedAt=new Date().toISOString();data.points+=(t.points||0);save();toast('تم الإنجاز +'+(t.points||0)+' نقطة')}}const edit=e.target.closest('[data-edit]');if(edit)openTask(data.tasks.find(t=>t.id===edit.dataset.edit));const add=e.target.closest('[data-add-task]');if(add)openTask();if(e.target.id==='flySave'&&pendingFly){data.tasks.push({...pendingFly,id:id()});pendingFly=null;$('#flyPreview').classList.remove('show');$('#flyInput').value='';save();toast('تمت إضافة المهمة')}if(e.target.id==='flyEdit'&&pendingFly){const t={...pendingFly,id:''};openTask(t)}const red=e.target.closest('[data-redeem]');if(red){const r=data.rewards.find(x=>x.id===red.dataset.redeem);if(r&&data.points>=r.points){data.points-=r.points;save();toast('تستاهل '+r.name)}}});
 function showView(v){$$('.view').forEach(x=>x.classList.toggle('active',x.dataset.viewPanel===v));document.body.classList.remove('sidebar-open')}
 $('#newTaskBtn').onclick=()=>openTask();$('#quickTaskForm').onsubmit=e=>{e.preventDefault();const title=$('#quickTaskInput').value.trim();if(!title)return;data.tasks.push({...parseFly(title),id:id()});$('#quickTaskInput').value='';save();toast('أضيفت للوارد')};$('#taskForm').onsubmit=e=>{e.preventDefault();const tid=$('#taskId').value;const obj={title:$('#taskTitle').value.trim(),notes:$('#taskNotes').value.trim(),spaceId:$('#taskSpace').value,personId:$('#taskPerson').value,status:$('#taskStatus').value,priority:$('#taskPriority').value,due:$('#taskDue').value,follow:$('#taskFollow').value,points:Number($('#taskPoints').value),createdAt:new Date().toISOString()};if(tid){const i=data.tasks.findIndex(t=>t.id===tid);data.tasks[i]={...data.tasks[i],...obj}}else data.tasks.push({...obj,id:id()});$('#taskModal').close();save();toast('تم الحفظ')};$('#deleteTaskBtn').onclick=()=>{const tid=$('#taskId').value;if(tid){data.tasks=data.tasks.filter(t=>t.id!==tid);$('#taskModal').close();save();toast('تم الحذف')}};
 function simple(type){$('#simpleType').value=type;$('#simpleName').value='';$('#simpleTitle').textContent=type==='space'?'مساحة جديدة':type==='person'?'شخص جديد':'مكافأة جديدة';$('#simpleExtraField').hidden=type!=='reward';$('#simpleModal').showModal()}
 $('#addSpaceBtn').onclick=$('#quickAddSpace').onclick=()=>simple('space');$('#addPersonBtn').onclick=()=>simple('person');$('#addRewardBtn').onclick=()=>simple('reward');$('#simpleForm').onsubmit=e=>{e.preventDefault();const type=$('#simpleType').value,name=$('#simpleName').value.trim();if(type==='space')data.spaces.push({id:id(),name});if(type==='person')data.people.push({id:id(),name});if(type==='reward')data.rewards.push({id:id(),name,points:Number($('#simpleExtra').value)||50});$('#simpleModal').close();save()};
 $('#profileForm').onsubmit=e=>{e.preventDefault();data.profile={name:$('#profileName').value.trim(),email:$('#profileEmail').value.trim()};save();toast('تم حفظ بياناتك');showView('today')};
 $('#manageExportBtn').onclick=()=>$('#exportBtn').click();
 $('#manageImportInput').onchange=async e=>{try{data=JSON.parse(await e.target.files[0].text());save();toast('تمت الاستعادة')}catch{toast('ملف غير صالح')}};

 $('#themeBtn').onclick=()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;localStorage.setItem('mesraah_theme',next)};document.documentElement.dataset.theme=localStorage.getItem('mesraah_theme')||'light';$('#mobileMenu').onclick=()=>document.body.classList.toggle('sidebar-open');$$('#todayFilters button').forEach(b=>b.onclick=()=>{$$('#todayFilters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;renderToday()});$('#globalSearch').addEventListener('input',e=>{const q=e.target.value.trim();if(!q)return;showView('search');$('#searchTitle').textContent='البحث عن: '+q;$('#searchResults').innerHTML=activeTasks().filter(t=>t.title.includes(q)).map(taskHTML).join('')||'<div class="empty-state"><h3>ما لقيت نتيجة</h3></div>'});
 $('#exportBtn').onclick=()=>{const b=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='mesraah-backup.json';a.click();URL.revokeObjectURL(a.href)};$('#importInput').onchange=async e=>{try{data=JSON.parse(await e.target.files[0].text());save();toast('تمت الاستعادة')}catch{toast('ملف غير صالح')}};
 const d=new Date();$('#todayDate').textContent=d.toLocaleDateString('ar-SA',{weekday:'long',day:'numeric',month:'long'});
 initFly();renderAll();
 if(!(data.profile&&data.profile.name)){
  $$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view==='manage'));
  showView('manage');
 }
})();