(() => {
 const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
 const KEY='mesraah_v030';
 const DEMO_VERSION=1;
 const POINTS_SCHEMA_VERSION=1;
 const seed={profile:{name:'',email:''},points:0,pointLedger:[],pointsSchemaVersion:POINTS_SCHEMA_VERSION,spaces:[{id:'personal',name:'شخصي'},{id:'work',name:'العمل'},{id:'family',name:'العائلة'}],people:[],rewards:[{id:'r1',name:'قهوة ومشوار',points:50},{id:'r2',name:'عشاء',points:100}],tasks:[],demoVersion:0};
 let data=load(); try{localStorage.setItem(KEY,JSON.stringify(data))}catch{} let filter='all'; let pendingFly=null; let currentEntity=null;
 function load(){try{const raw=localStorage.getItem(KEY);if(!raw)return structuredClone(seed);return migratePoints({...seed,...JSON.parse(raw)})}catch{return structuredClone(seed)}}
 function pointTotals(state=data){const ledger=Array.isArray(state.pointLedger)?state.pointLedger:[];const earned=Math.max(0,ledger.filter(entry=>entry.scope==='task').reduce((sum,entry)=>sum+(Number(entry.amount)||0),0));const spent=Math.max(0,-ledger.filter(entry=>entry.scope==='reward').reduce((sum,entry)=>sum+(Number(entry.amount)||0),0));return {earned,spent,available:Math.max(0,earned-spent)}}
 function syncPoints(state=data){state.pointLedger=Array.isArray(state.pointLedger)?state.pointLedger:[];state.pointsSchemaVersion=POINTS_SCHEMA_VERSION;state.points=pointTotals(state).available;return state.points}
 function migratePoints(state){state.tasks=Array.isArray(state.tasks)?state.tasks:[];if(Number(state.pointsSchemaVersion)>=POINTS_SCHEMA_VERSION){syncPoints(state);return state}const legacyBalance=Math.max(0,(Number(state.points)||0)-35);const ledger=[];let earned=0;state.tasks.forEach(task=>{if(task.status!=='done'||task.demo)return;const amount=Math.max(0,Number(task.points)||0);if(!amount)return;task.pointsCycle=Math.max(1,Number(task.pointsCycle)||1);earned+=amount;ledger.push({id:`task-${task.id}-${task.pointsCycle}-legacy`,scope:'task',type:'task_earn',taskId:String(task.id),taskTitle:task.title||'مهمة منجزة',amount,at:task.completedAt||task.createdAt||new Date().toISOString()})});const inferredSpent=Math.max(0,earned-Math.min(earned,legacyBalance));if(inferredSpent)ledger.push({id:'points-migration-rewards',scope:'reward',type:'legacy_redeem',rewardName:'مكافآت مستخدمة سابقا',amount:-inferredSpent,at:new Date().toISOString()});state.pointLedger=ledger;syncPoints(state);return state}
 function save(){syncPoints(data);localStorage.setItem(KEY,JSON.stringify(data));renderAll()}
 function replaceTasks(tasks,fields={}){const next=Array.isArray(tasks)?tasks:[],previous=new Map(data.tasks.map(task=>[String(task.id),task])),nextIds=new Set(next.map(task=>String(task.id)));data.tasks.filter(task=>!nextIds.has(String(task.id))).forEach(task=>{const credit=Math.max(0,taskCredit(task.id));if(credit)addPointEntry({id:`task-${task.id}-${Math.max(1,Number(task.pointsCycle)||1)}-delete`,scope:'task',type:'task_delete',taskId:String(task.id),taskTitle:task.title||'مهمة',amount:-credit})});next.forEach(task=>reconcileTaskCredit(previous.get(String(task.id))||null,task));data={...data,...fields,tasks:next};save()}
 function id(){return Math.random().toString(36).slice(2,9)}
 function today(){return new Date().toISOString().slice(0,10)}
 function addDays(date,n){const d=new Date(date+'T12:00:00');d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)}
 function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1700)}
 function esc(s=''){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
 function addPointEntry(entry){data.pointLedger=Array.isArray(data.pointLedger)?data.pointLedger:[];if(data.pointLedger.some(item=>String(item.id)===String(entry.id)))return;data.pointLedger.push({...entry,at:entry.at||new Date().toISOString()})}
 function taskCredit(taskId){return (data.pointLedger||[]).filter(entry=>entry.scope==='task'&&String(entry.taskId)===String(taskId)).reduce((sum,entry)=>sum+(Number(entry.amount)||0),0)}
 function reconcileTaskCredit(previous,task){const before=Math.max(0,taskCredit(task.id));const shouldCredit=task.status==='done'&&!task.demo;const desired=shouldCredit?Math.max(0,Number(task.points)||0):0;if(previous?.status!=='done'&&task.status==='done'){task.completedAt=new Date().toISOString();task.pointsCycle=Math.max(0,Number(task.pointsCycle)||0)+1}else if(task.status!=='done')task.completedAt='';const delta=desired-before;if(!delta)return;const cycle=Math.max(1,Number(task.pointsCycle)||1);const type=task.status!=='done'?'task_reopen':previous?.status==='done'?'task_adjust':'task_earn';const suffix=type==='task_earn'?'earn':type==='task_reopen'?'reopen':`adjust-${Date.now()}`;addPointEntry({id:`task-${task.id}-${cycle}-${suffix}`,scope:'task',type,taskId:String(task.id),taskTitle:task.title||'مهمة',amount:delta})}
 function deleteTasksWithCredits(ids){const targets=new Set([...ids].map(String));data.tasks.filter(task=>targets.has(String(task.id))).forEach(task=>{const credit=Math.max(0,taskCredit(task.id));if(credit)addPointEntry({id:`task-${task.id}-${Math.max(1,Number(task.pointsCycle)||1)}-delete`,scope:'task',type:'task_delete',taskId:String(task.id),taskTitle:task.title||'مهمة',amount:-credit})});data.tasks=data.tasks.filter(task=>!targets.has(String(task.id)))}
 function ensureExamples(){
  if((data.demoVersion||0)>=DEMO_VERSION)return;
  const td=today(), now=new Date().toISOString();
  const addSpace=(sid,name)=>{if(!data.spaces.some(s=>s.id===sid))data.spaces.push({id:sid,name,demo:true})};
  addSpace('social','اجتماعي'); addSpace('volunteer','تطوعي');
  const demoPeople=[{id:'demo-ahmed',name:'أحمد',demo:true},{id:'demo-sara',name:'سارة',demo:true},{id:'demo-khaled',name:'خالد',demo:true}];
  demoPeople.forEach(p=>{if(!data.people.some(x=>x.id===p.id))data.people.push(p)});
  const examples=[
   {id:'demo-personal',title:'حجز موعد فحص السيارة',spaceId:'personal',personId:'',status:'active',priority:'normal',due:td,follow:'',points:10},
   {id:'demo-work',title:'مراجعة العرض قبل إرساله للعميل',spaceId:'work',personId:'demo-ahmed',status:'active',priority:'important',due:td,follow:'',points:20},
   {id:'demo-family',title:'ترتيب موعد العائلة لنهاية الأسبوع',spaceId:'family',personId:'',status:'inbox',priority:'normal',due:addDays(td,2),follow:'',points:10},
   {id:'demo-social',title:'الاتصال بصديق والاطمئنان عليه',spaceId:'social',personId:'demo-khaled',status:'active',priority:'normal',due:addDays(td,1),follow:'',points:5},
   {id:'demo-volunteer',title:'تأكيد المشاركة في المبادرة التطوعية',spaceId:'volunteer',personId:'demo-sara',status:'active',priority:'important',due:addDays(td,1),follow:'',points:20},
   {id:'demo-follow',title:'متابعة الرد على خطاب الشراكة',spaceId:'work',personId:'demo-ahmed',status:'waiting',priority:'important',due:addDays(td,-1),follow:addDays(td,2),points:20},
   {id:'demo-done',title:'إنهاء ترتيب مهام الأسبوع',spaceId:'personal',personId:'',status:'done',priority:'normal',due:td,follow:'',points:10,completedAt:now}
  ];
  examples.forEach(t=>{if(!data.tasks.some(x=>x.id===t.id))data.tasks.push({...t,notes:'',createdAt:now,demo:true})});
  data.demoVersion=DEMO_VERSION;
  try{localStorage.setItem(KEY,JSON.stringify(data))}catch{}
 }
 function clearExamples(){
  data.tasks=data.tasks.filter(t=>!t.demo);
  data.people=data.people.filter(p=>!p.demo);
  const demoSpaceIds=new Set(data.spaces.filter(s=>s.demo).map(s=>s.id));
  const used=new Set(data.tasks.map(t=>t.spaceId).filter(Boolean));
  data.spaces=data.spaces.filter(s=>!s.demo||used.has(s.id));
  data.demoVersion=DEMO_VERSION;
  save();toast('تم مسح الأمثلة');
 }
 function hasExamples(){return data.tasks.some(t=>t.demo)||data.people.some(p=>p.demo)||data.spaces.some(s=>s.demo)}
 ensureExamples();
 function taskHTML(t){const sp=data.spaces.find(x=>x.id===t.spaceId);const pe=data.people.find(x=>x.id===t.personId);const done=t.status==='done';const late=t.due&&t.due<today()&&!done;const tone=done?'is-done':late?'is-late':t.status==='waiting'?'is-waiting':['important','strategic'].includes(t.priority)?'is-important':'';return `<article class="task-item ${tone}" data-task="${t.id}"><button class="task-check" ${done?'disabled aria-label="مهمة منجزة"':`data-done="${t.id}" aria-label="إنجاز المهمة"`}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m7.5 12 3 3 6-7"/></svg></button><div class="task-content"><div class="task-title">${esc(t.title)}</div><div class="task-meta">${sp?`<span class="chip"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="5" y="5" width="6" height="6" rx="1.5"/><rect x="13" y="5" width="6" height="6" rx="1.5"/><rect x="5" y="13" width="6" height="6" rx="1.5"/><rect x="13" y="13" width="6" height="6" rx="1.5"/></svg>${esc(sp.name)}</span>`:''}${pe?`<span class="chip"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="8" r="3"/><path d="M6.5 19c.5-3.5 2.3-5 5.5-5s5 1.5 5.5 5"/></svg>${esc(pe.name)}</span>`:''}${t.due?`<span class="chip ${late?'red':''}">${t.due}</span>`:''}${t.status==='waiting'?'<span class="chip gold">انتظار</span>':''}${done?`<span class="chip green">منجزة</span><span class="chip gold">+${t.demo?0:(t.points||0)} نقطة</span>`:''}${t.demo?'<span class="chip demo-chip">مثال</span>':''}</div></div><button class="task-more" data-edit="${t.id}" aria-label="تعديل المهمة"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="5" cy="12" r="1.5"/><circle cx="12" cy="12" r="1.5"/><circle cx="19" cy="12" r="1.5"/></svg></button></article>`}
 function activeTasks(){const finishedThrough=new Map();data.tasks.forEach(t=>{const series=String(t.recurrenceSeriesId||'');if(!series||t.status!=='done'||!t.due)return;const saved=finishedThrough.get(series)||'';if(t.due>saved)finishedThrough.set(series,t.due)});const occurrences=new Set();return data.tasks.filter(t=>{if(t.status==='done')return false;const series=String(t.recurrenceSeriesId||'');if(series&&t.due&&t.due<=(finishedThrough.get(series)||''))return false;const occurrence=series&&t.recurrenceOccurrence?`${series}:${t.recurrenceOccurrence}`:'';if(occurrence){if(occurrences.has(occurrence))return false;occurrences.add(occurrence)}return true})}
 function renderAll(){renderSpaces();renderToday();renderInbox();renderPeople();renderFollowups();renderAchievements();renderRewards();renderManage();fillSelects();renderEntity()}
 function renderSpaces(){$('#spaceGrid').innerHTML=data.spaces.map(s=>{const n=activeTasks().filter(t=>t.spaceId===s.id).length;const color=s.color||'#0d3656';return `<article class="space-card entity-card" style="--entity-color:${esc(color)}"><button type="button" class="entity-card-main" data-open-entity="space" data-entity-id="${esc(s.id)}" aria-label="عرض مهام مساحة ${esc(s.name)}"><span class="entity-color" aria-hidden="true"></span><span><h3>${esc(s.name)}</h3><p>${n} مهمة مفتوحة${s.demo?' · مثال':''}</p></span><b aria-hidden="true">←</b></button></article>`}).join('')}
 function renderToday(){const tasks=activeTasks().filter(t=>t.due===today()||(!t.due&&t.status==='active'));const shown=tasks.filter(t=>filter==='all'||(filter==='important'&&['important','strategic'].includes(t.priority))||(filter==='waiting'&&t.status==='waiting'));$('#todayTaskList').innerHTML=shown.map(taskHTML).join('');$('#todayEmpty').hidden=shown.length>0;const done=data.tasks.filter(t=>t.status==='done'&&t.completedAt?.slice(0,10)===today()).length;const late=activeTasks().filter(t=>t.due&&t.due<today()).length;const waiting=activeTasks().filter(t=>t.status==='waiting').length;$('#statToday').textContent=tasks.length;$('#statLate').textContent=late;$('#statWaiting').textContent=waiting;$('#statDone').textContent=done;$('#todayNavCount').textContent=tasks.length;$('#followNavCount').textContent=waiting;const pct=tasks.length+done?Math.round(done/(tasks.length+done)*100):0;$('#dayProgress').textContent=pct+'%';$('.day-ring').style.setProperty('--progress',pct+'%');$('#pointsBalance').textContent=data.points;const focus=[...activeTasks()].filter(t=>!t.due||t.due>=today()).sort((a,b)=>(b.priority==='strategic')-(a.priority==='strategic')||(a.due||'9999').localeCompare(b.due||'9999'))[0];$('#focusTask').innerHTML=focus?`<div class="focus-box"><h3>${esc(focus.title)}</h3><p>${focus.due?'موعدها '+focus.due:'بدون موعد محدد'}</p></div>`:'<div class="focus-box"><h3>لا توجد مهمة تالية</h3><p>المهام الماضية تجدها ضمن المتأخرة.</p></div>';const wr=activeTasks().filter(t=>t.status==='waiting').slice(0,6);$('#waitingList').innerHTML=wr.map(t=>`<article class="waiting-card"><h3>${esc(t.title)}</h3><p>${t.follow?'متابعة '+t.follow:'بانتظار رد'}</p></article>`).join('')||'<article class="waiting-card"><h3>ما فيه شيء معلق</h3><p>ممتاز.</p></article>';renderNextReward()}
 function renderNextReward(){if(!data.rewards.length){$('#pointsTrack').style.width='0';$('#nextReward').innerHTML='<div class="reward-next">أضف مكافأة وحدد نقاطها.</div>';return}const next=[...data.rewards].filter(r=>r.points>data.points).sort((a,b)=>a.points-b.points)[0];if(next){const pct=Math.min(100,Math.round(data.points/next.points*100));$('#pointsTrack').style.width=pct+'%';$('#nextReward').innerHTML=`<div class="reward-next">باقي ${next.points-data.points} نقطة إلى ${esc(next.name)}</div>`}else{$('#pointsTrack').style.width='100%';$('#nextReward').innerHTML='<div class="reward-next">عندك رصيد لمكافأة.</div>'}}
 function renderInbox(){const arr=activeTasks().filter(t=>t.status==='inbox');$('#inboxList').innerHTML=arr.map(taskHTML).join('');$('#inboxEmpty').hidden=arr.length>0;$('#inboxNavCount').textContent=arr.length}
 function renderPeople(){const counts=p=>activeTasks().filter(t=>t.personId===p.id).length;$('#peopleGrid').innerHTML=data.people.map(p=>`<article class="person-card entity-card"><button type="button" class="entity-card-main" data-open-entity="person" data-entity-id="${esc(p.id)}" aria-label="عرض المهام المرتبطة بـ ${esc(p.name)}"><span class="entity-avatar" aria-hidden="true">${esc((p.name||'؟').trim().charAt(0)||'؟')}</span><span><h3>${esc(p.name)}</h3><p>${counts(p)} مهمة مرتبطة${p.demo?' · مثال':''}</p></span><b aria-hidden="true">←</b></button></article>`).join('')||'<article class="person-card"><h3>أضف أول شخص</h3><p>تظهر تحته كل المهام والمتابعات.</p></article>'}
 function renderFollowups(){const arr=activeTasks().filter(t=>t.follow||t.status==='waiting').sort((a,b)=>(a.follow||'9999').localeCompare(b.follow||'9999'));$('#followupList').innerHTML=arr.map(taskHTML).join('')||'<div class="empty-state"><span>↻</span><h3>ما فيه متابعة</h3></div>'}
 function renderAchievements(){const done=data.tasks.filter(t=>t.status==='done');const now=new Date();const weekStart=new Date(now);weekStart.setDate(now.getDate()-6);$('#achToday').textContent=done.filter(t=>t.completedAt?.slice(0,10)===today()).length;$('#achWeek').textContent=done.filter(t=>t.completedAt&&new Date(t.completedAt)>=weekStart).length;$('#achAll').textContent=done.length;$('#achPoints').textContent=pointTotals().earned;$('#achievementList').innerHTML=done.slice().reverse().map(taskHTML).join('')||'<div class="empty-state"><h3>أول إنجاز يبدأ من أول مهمة.</h3></div>'}
 function pointEntryText(entry){const name=entry.taskTitle||entry.rewardName||'حركة نقاط';if(entry.type==='task_earn')return `إنجاز: ${name}`;if(entry.type==='task_adjust')return `تعديل نقاط: ${name}`;if(entry.type==='task_reopen')return `إعادة فتح: ${name}`;if(entry.type==='task_delete')return `حذف مهمة منجزة: ${name}`;if(entry.type==='reward_redeem')return `استخدام مكافأة: ${name}`;if(entry.type==='legacy_redeem')return name;return name}
 function pointEntryDate(value){const date=new Date(value);return Number.isNaN(date.getTime())?'':date.toLocaleDateString('en-GB',{day:'2-digit',month:'2-digit',year:'numeric'})}
 function renderRewards(){const totals=pointTotals();$('#rewardBalance').textContent=totals.available;$('#rewardEarned').textContent=totals.earned;$('#rewardSpent').textContent=totals.spent;$('#rewardGrid').innerHTML=data.rewards.map(r=>`<article class="reward-card"><div class="reward-card-head"><div><h3>${esc(r.name)}</h3><p>${r.points} نقطة</p></div><div class="reward-card-actions"><button type="button" data-edit-reward="${r.id}">تعديل</button><button type="button" data-delete-reward="${r.id}">حذف</button></div></div><button class="secondary-btn reward-use-btn" data-redeem="${r.id}" ${totals.available<r.points?'disabled':''}>استخدم</button></article>`).join('')||'<div class="empty-state reward-empty"><h3>أضف مكافأة تستحق الوصول لها</h3></div>';const history=[...(data.pointLedger||[])].sort((a,b)=>String(b.at||'').localeCompare(String(a.at||''))).slice(0,30);$('#pointsHistory').innerHTML=history.map(entry=>`<article class="points-history-row"><span class="points-history-mark ${Number(entry.amount)>=0?'is-credit':'is-debit'}">${Number(entry.amount)>=0?'+':''}${Number(entry.amount)||0}</span><div><strong>${esc(pointEntryText(entry))}</strong><small>${pointEntryDate(entry.at)}</small></div></article>`).join('')||'<div class="empty-state points-history-empty"><h3>تبدأ الحركات مع أول إنجاز</h3></div>'}
 function renderManage(){
  data.profile=data.profile||{name:'',email:''};
  $('#profileName').value=data.profile.name||'';
  $('#profileEmail').value=data.profile.email||'';
  $('#manageSpacesCount').textContent=data.spaces.length+' جهة أو مساحة';
  $('#managePeopleCount').textContent=data.people.length+' شخص';
  $('#manageRewardsCount').textContent=data.rewards.length+' مكافأة';
  const clear=$('#clearExamplesBtn');if(clear){clear.hidden=!hasExamples();clear.disabled=!hasExamples()}
  const ready=Boolean(data.profile.name);
  $('#manageStatus').textContent=ready?'تم إعداد الحساب':'الإعداد الأول';
  const h=new Date().getHours();
  $('#greeting').textContent=ready?((h<12?'صباح الخير':'مساء الخير')+' يا '+data.profile.name):'أهلًا بك في مِسراح';
 }
 function fillSelects(){const sp='<option value="">بدون مساحة</option>'+data.spaces.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('');const pe='<option value="">بدون شخص</option>'+data.people.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');$('#taskSpace').innerHTML=sp;$('#taskPerson').innerHTML=pe}
 function entityCollection(kind){return kind==='space'?data.spaces:data.people}
 function entityField(kind){return kind==='space'?'spaceId':'personId'}
 function getEntity(kind,idValue){return entityCollection(kind).find(item=>String(item.id)===String(idValue))}
 function linkedTasks(kind,idValue){const field=entityField(kind);return data.tasks.filter(task=>String(task[field]||'')===String(idValue))}
 function showEntity(kind,idValue){if(!getEntity(kind,idValue))return;currentEntity={kind,id:String(idValue)};showView('entity');renderEntity();window.scrollTo({top:0,behavior:'smooth'})}
 function renderEntity(){const host=$('#entityTaskList');if(!host)return;if(!currentEntity){host.innerHTML='';return}const kind=currentEntity.kind,entity=getEntity(kind,currentEntity.id);if(!entity){currentEntity=null;showView(kind==='space'?'spaces':'people');return}const tasks=linkedTasks(kind,currentEntity.id);const open=tasks.filter(task=>task.status!=='done');const done=tasks.filter(task=>task.status==='done');$('#entityEyebrow').textContent=kind==='space'?'مهام المساحة':'المهام المرتبطة بالشخص';$('#entityTitle').textContent=entity.name||'';$('#entitySummary').textContent=`${open.length} مفتوحة · ${done.length} منجزة`;const mark=$('#entityMark');mark.className=kind==='space'?'entity-detail-mark is-space':'entity-detail-mark is-person';mark.textContent=kind==='space'?'':((entity.name||'؟').trim().charAt(0)||'؟');mark.style.setProperty('--entity-color',entity.color||'#0d3656');host.innerHTML=tasks.length?`<div class="entity-task-group"><div class="entity-task-heading"><h2>المهام المفتوحة</h2><span>${open.length}</span></div>${open.length?open.map(taskHTML).join(''):'<div class="entity-list-empty">لا توجد مهام مفتوحة</div>'}</div><div class="entity-task-group is-completed"><div class="entity-task-heading"><h2>المهام المنجزة</h2><span>${done.length}</span></div>${done.length?done.map(taskHTML).join(''):'<div class="entity-list-empty">لا توجد مهام منجزة</div>'}</div>`:'<div class="empty-state entity-empty"><span>＋</span><h3>لا توجد مهام مرتبطة</h3><p>اختر هذا الشخص أو المساحة عند إضافة مهمة، وستظهر هنا.</p></div>'}
 function openEntityEdit(){if(!currentEntity)return;const entity=getEntity(currentEntity.kind,currentEntity.id);if(!entity)return;$('#entityEditKind').value=currentEntity.kind;$('#entityEditId').value=entity.id;$('#entityEditName').value=entity.name||'';$('#entityEditTitle').textContent=currentEntity.kind==='space'?'تعديل المساحة':'تعديل الشخص';$('#entityEditEyebrow').textContent=currentEntity.kind==='space'?'المساحات':'الأشخاص';$('#entitySpaceFields').hidden=currentEntity.kind!=='space';$('#entityPersonFields').hidden=currentEntity.kind!=='person';$('#entityEditColor').value=entity.color||'#0d3656';$('#entityEditRelation').value=entity.relation||'';$('#entityEditCity').value=entity.city||'';$('#entityEditOrganization').value=entity.organization||'';$('#entityEditNote').value=entity.note||'';$('#entityEditModal').showModal()}
 function openEntityDelete(){if(!currentEntity)return;const entity=getEntity(currentEntity.kind,currentEntity.id);if(!entity)return;const tasks=linkedTasks(currentEntity.kind,currentEntity.id);const alternatives=entityCollection(currentEntity.kind).filter(item=>String(item.id)!==String(entity.id));$('#entityDeleteKind').value=currentEntity.kind;$('#entityDeleteId').value=entity.id;$('#entityDeleteTitle').textContent=`حذف ${currentEntity.kind==='space'?'المساحة':'الشخص'} «${entity.name}»`;$('#entityDeleteSummary').textContent=tasks.length?`مرتبط به ${tasks.length} مهمة. اختر مصيرها قبل الحذف.`:'لا توجد مهام مرتبطة. يتطلب الحذف تأكيدا نهائيا.';$('#entityMoveTarget').innerHTML=alternatives.map(item=>`<option value="${esc(item.id)}">${esc(item.name)}</option>`).join('');const moveRadio=$('#entityDeleteForm input[value="move"]');moveRadio.disabled=!alternatives.length;moveRadio.closest('label').classList.toggle('is-disabled',!alternatives.length);$('#entityDeleteForm input[value="unlink"]').checked=true;$('#entityMoveField').hidden=true;$('#entityDeleteModal').showModal()}
 function openTask(t=null){$('#taskForm').reset();$('#taskId').value=t?.id||'';$('#taskModalTitle').textContent=t?'تعديل المهمة':'مهمة جديدة';$('#deleteTaskBtn').hidden=!t;if(t){$('#taskTitle').value=t.title||'';$('#taskNotes').value=t.notes||'';$('#taskSpace').value=t.spaceId||'';$('#taskPerson').value=t.personId||'';$('#taskStatus').value=t.status||'inbox';$('#taskPriority').value=t.priority||'normal';$('#taskDue').value=t.due||'';$('#taskFollow').value=t.follow||'';$('#taskPoints').value=t.points||10}$('#taskModal').showModal()}
 function parseFly(text){text=text.trim();let due='',follow='',spaceId='',personId='';const td=today();if(/بكره|بكرة|غد/.test(text)) due=addDays(td,1);else if(/اليوم/.test(text)) due=td;const days={'الأحد':0,'الاحد':0,'الاثنين':1,'الثلاثاء':2,'الأربعاء':3,'الاربعاء':3,'الخميس':4,'الجمعة':5,'السبت':6};for(const [name,idx] of Object.entries(days)){if(text.includes(name)){const d=new Date();const delta=(idx-d.getDay()+7)%7||7;due=addDays(td,delta);break}}const fm=text.match(/بعد\s+(\d+)\s+يوم/);if(fm) follow=addDays(due||td,Number(fm[1]));for(const s of data.spaces){if(text.includes(s.name)){spaceId=s.id;break}}for(const p of data.people){if(text.includes(p.name)){personId=p.id;break}}let title=text.replace(/(?:اليوم|بكره|بكرة|غدًا|غدا)/g,'').replace(/بعد\s+\d+\s+يوم(?:ين)?/g,'').replace(/\s+/g,' ').trim();return {title,due,follow,spaceId,personId,status:'inbox',priority:/مهم|عاجل/.test(text)?'important':'normal',points:10,notes:'',createdAt:new Date().toISOString()}}
 function showFlyPreview(t){pendingFly=t;const sp=data.spaces.find(s=>s.id===t.spaceId);const pe=data.people.find(p=>p.id===t.personId);$('#flyPreview').innerHTML=`<strong>${esc(t.title)}</strong><small>${[sp?.name,pe?.name,t.due&&'الموعد '+t.due,t.follow&&'المتابعة '+t.follow].filter(Boolean).join(' • ')||'ستدخل إلى الوارد'}</small><div class="fly-actions"><button class="fly-save" id="flySave">حفظ</button><button class="fly-edit" id="flyEdit">تعديل</button></div>`;$('#flyPreview').classList.add('show')}
 function initFly(){const btn=$('#flyVoice'),input=$('#flyInput'),send=$('#flySend');if(!btn||!input||!send)return;const go=()=>{if(!input.value.trim())return;showFlyPreview(parseFly(input.value))};send.onclick=go;input.addEventListener('keydown',e=>{if(e.key==='Enter')go()});const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){btn.onclick=()=>{input.focus();toast('الإدخال الصوتي يحتاج متصفح يدعم المايك')};return}btn.onclick=()=>{const r=new SR();r.lang='ar-SA';r.interimResults=false;btn.classList.add('listening');r.start();r.onresult=e=>{input.value=e.results[0][0].transcript;showFlyPreview(parseFly(input.value))};r.onend=()=>btn.classList.remove('listening');r.onerror=()=>{btn.classList.remove('listening');toast('تعذر تشغيل المايك')}}}
 function installEnhancements(){
  const actions=$('.manage-data-actions');if(actions&&!$('#clearExamplesBtn')){const b=document.createElement('button');b.type='button';b.id='clearExamplesBtn';b.className='secondary-btn clear-examples-btn';b.textContent='مسح الأمثلة';actions.appendChild(b);b.onclick=clearExamples}
  if(!$('.mesraah-footer')){
   const footer=document.createElement('footer');footer.className='mesraah-footer';footer.innerHTML=`<div class="mesraah-footer-shell"><div class="mesraah-footer-main"><div class="mesraah-footer-brand"><img src="https://almohammdin.github.io/emtidad/assets/images/naif-logo.png" alt="شعار نايف المحمدي"><p>مستشار الحوكمة وتطوير الأعمال</p></div><div class="mesraah-footer-social"><div class="mesraah-social-links" aria-label="حسابات التواصل"><a href="https://x.com/almohammdin" target="_blank" rel="noopener" aria-label="X" title="X"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4.4 3h4.8l3.8 5.1L17.5 3H20l-5.9 6.9L20.5 21h-4.8l-4.2-5.7L6.6 21H4l6.3-7.5L4.4 3Zm3.7 2 8.5 14h1.8L9.9 5H8.1Z"/></svg></a><a href="https://www.linkedin.com/in/almohammdin/" target="_blank" rel="noopener" aria-label="LinkedIn" title="LinkedIn"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5.2 8.4h3.2V19H5.2V8.4Zm1.6-5.2a1.9 1.9 0 1 1 0 3.8 1.9 1.9 0 0 1 0-3.8Zm3.8 5.2h3.1v1.5h.1c.5-.8 1.6-1.8 3.5-1.8 3.3 0 4 2.2 4 5.1V19H18v-5.2c0-1.2 0-2.8-1.8-2.8s-2 1.3-2 2.7V19h-3.3V8.4Z"/></svg></a><a href="https://www.snapchat.com/add/almohammdin" target="_blank" rel="noopener" aria-label="Snapchat" title="Snapchat"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8.2 16.9c.8.3 1.1.7 1.3 1.1.7-.1 1.5-.2 2.5-.2s1.8.1 2.5.2c.2-.4.5-.8 1.3-1.1 1.2-.4 2.1-1 2.5-1.6-1.9-.7-2.1-2.3-2.1-4.7 0-2.7-1.7-4.5-4.2-4.5s-4.2 1.8-4.2 4.5c0 2.4-.2 4-2.1 4.7.4.6 1.3 1.2 2.5 1.6Z"/></svg></a><a href="https://linktr.ee/almohammdin" target="_blank" rel="noopener" aria-label="Linktree" title="Linktree"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M13.736 5.852 17.644 2l1.92 1.92-3.852 3.736h5.644v2.736h-5.66l3.868 3.752-1.92 1.92-5.276-5.28-5.276 5.28-1.92-1.92 3.868-3.752H3.38V7.656h5.644L5.172 3.92 7.092 2l3.932 3.852V0h2.712v5.852ZM11.024 24v-8.604h2.712V24h-2.712Z"/></svg></a></div><a class="mesraah-social-handle" href="https://linktr.ee/almohammdin" target="_blank" rel="noopener">Almohammdin</a></div></div><div class="mesraah-footer-bottom"><span>مِسراح لإدارة المهام والإنجاز</span><span>آخر تحديث: أغسطس 2026</span><span>v0.4.1</span></div></div>`;
   $('.main').appendChild(footer)
  }
 }
 function openRewardAction(action,rewardId){const reward=data.rewards.find(item=>String(item.id)===String(rewardId));if(!reward)return;$('#rewardAction').value=action;$('#rewardActionId').value=reward.id;$('#rewardActionTitle').textContent=action==='redeem'?`استخدام «${reward.name}»`:`حذف «${reward.name}»`;$('#rewardActionText').textContent=action==='redeem'?`سيخصم ${reward.points} نقطة من رصيدك المتاح.`:'تحذف المكافأة من القائمة، ويبقى سجل استخدامها السابق.';const confirm=$('#rewardActionConfirm');confirm.textContent=action==='redeem'?'تأكيد الاستخدام':'تأكيد الحذف';confirm.classList.toggle('entity-confirm-delete',action==='delete');confirm.classList.toggle('primary-btn',action==='redeem');$('#rewardActionModal').showModal()}
 document.addEventListener('click',e=>{const close=e.target.closest('[data-close-dialog]');if(close){close.closest('dialog')?.close();return}const nav=e.target.closest('[data-view]');if(nav){$$('.nav-item').forEach(x=>x.classList.remove('active'));nav.classList.add('active');currentEntity=null;showView(nav.dataset.view)}const open=e.target.closest('[data-open-view]');if(open){currentEntity=null;showView(open.dataset.openView)}const entityOpen=e.target.closest('[data-open-entity]');if(entityOpen)showEntity(entityOpen.dataset.openEntity,entityOpen.dataset.entityId);if(e.target.closest('#entityBackBtn')&&currentEntity){const target=currentEntity.kind==='space'?'spaces':'people';currentEntity=null;showView(target)}if(e.target.closest('#entityEditBtn'))openEntityEdit();if(e.target.closest('#entityDeleteBtn'))openEntityDelete();const done=e.target.closest('[data-done]');if(done){const t=data.tasks.find(x=>x.id===done.dataset.done);if(t&&t.status!=='done'){const previous={...t};t.status='done';reconcileTaskCredit(previous,t);save();toast('تم الإنجاز +'+(t.demo?0:(t.points||0))+' نقطة')}}const edit=e.target.closest('[data-edit]');if(edit)openTask(data.tasks.find(t=>t.id===edit.dataset.edit));const calendarTask=e.target.closest('[data-calendar-task]');if(calendarTask)openTask(data.tasks.find(t=>String(t.id)===String(calendarTask.dataset.calendarTask)));const add=e.target.closest('[data-add-task]');if(add)openTask();if(e.target.id==='flySave'&&pendingFly){data.tasks.push({...pendingFly,id:id()});pendingFly=null;$('#flyPreview').classList.remove('show');$('#flyInput').value='';save();toast('تمت إضافة المهمة')}if(e.target.id==='flyEdit'&&pendingFly){const t={...pendingFly,id:''};openTask(t)}const red=e.target.closest('[data-redeem]');if(red)openRewardAction('redeem',red.dataset.redeem);const rewardEdit=e.target.closest('[data-edit-reward]');if(rewardEdit)simple('reward',data.rewards.find(item=>String(item.id)===String(rewardEdit.dataset.editReward)));const rewardDelete=e.target.closest('[data-delete-reward]');if(rewardDelete)openRewardAction('delete',rewardDelete.dataset.deleteReward)});
 function showView(v){$$('.view').forEach(x=>x.classList.toggle('active',x.dataset.viewPanel===v));document.body.classList.remove('sidebar-open')}
 $('#newTaskBtn').onclick=()=>openTask();$('#quickTaskForm').onsubmit=e=>{e.preventDefault();const title=$('#quickTaskInput').value.trim();if(!title)return;data.tasks.push({...parseFly(title),id:id()});$('#quickTaskInput').value='';save();toast('أضيفت للوارد')};$('#taskForm').onsubmit=e=>{e.preventDefault();const tid=$('#taskId').value;const obj={title:$('#taskTitle').value.trim(),notes:$('#taskNotes').value.trim(),spaceId:$('#taskSpace').value,personId:$('#taskPerson').value,status:$('#taskStatus').value,priority:$('#taskPriority').value,due:$('#taskDue').value,follow:$('#taskFollow').value,points:Number($('#taskPoints').value),createdAt:new Date().toISOString()};if(tid){const i=data.tasks.findIndex(t=>t.id===tid),previous={...data.tasks[i]};data.tasks[i]={...data.tasks[i],...obj};reconcileTaskCredit(previous,data.tasks[i])}else{const task={...obj,id:id()};data.tasks.push(task);reconcileTaskCredit(null,task)}$('#taskModal').close();save();toast('تم الحفظ')};$('#deleteTaskBtn').onclick=()=>{const tid=$('#taskId').value;if(tid){deleteTasksWithCredits([tid]);$('#taskModal').close();save();toast('تم الحذف')}};
 function simple(type,item=null){$('#simpleType').value=type;$('#simpleId').value=item?.id||'';$('#simpleName').value=item?.name||'';$('#simpleExtra').value=type==='reward'?(item?.points||50):'';$('#simpleTitle').textContent=type==='space'?'مساحة جديدة':type==='person'?'شخص جديد':item?'تعديل المكافأة':'مكافأة جديدة';$('#simpleEyebrow').textContent=type==='reward'?'المكافآت':'';$('#simpleExtraLabel').textContent=type==='reward'?'النقاط':'التفاصيل';$('#simpleExtraField').hidden=type!=='reward';$('#simpleModal').showModal()}
 $('#addSpaceBtn').onclick=()=>simple('space');$('#addPersonBtn').onclick=()=>simple('person');$('#addRewardBtn').onclick=()=>simple('reward');$('#simpleForm').onsubmit=e=>{e.preventDefault();const type=$('#simpleType').value,itemId=$('#simpleId').value,name=$('#simpleName').value.trim();if(type==='space')data.spaces.push({id:id(),name,color:'#0d3656'});if(type==='person')data.people.push({id:id(),name});if(type==='reward'){const points=Math.max(1,Number($('#simpleExtra').value)||50),existing=data.rewards.find(item=>String(item.id)===String(itemId));if(existing){existing.name=name;existing.points=points}else data.rewards.push({id:id(),name,points})}$('#simpleModal').close();save();toast(type==='reward'&&itemId?'تم تعديل المكافأة':'تم الحفظ')};
 $('#rewardActionForm').onsubmit=e=>{e.preventDefault();const action=$('#rewardAction').value,reward=data.rewards.find(item=>String(item.id)===String($('#rewardActionId').value));if(!reward)return;if(action==='redeem'){if(pointTotals().available<reward.points){$('#rewardActionModal').close();toast('الرصيد المتاح أقل من قيمة المكافأة');return}addPointEntry({id:`reward-${reward.id}-${Date.now()}`,scope:'reward',type:'reward_redeem',rewardId:String(reward.id),rewardName:reward.name,amount:-Math.max(1,Number(reward.points)||0)});toast('تستاهل '+reward.name)}else{data.rewards=data.rewards.filter(item=>String(item.id)!==String(reward.id));toast('تم حذف المكافأة')}$('#rewardActionModal').close();save()};
 $('#entityEditForm').onsubmit=e=>{e.preventDefault();const kind=$('#entityEditKind').value,idValue=$('#entityEditId').value,entity=getEntity(kind,idValue),name=$('#entityEditName').value.trim();if(!entity||!name)return;entity.name=name;if(kind==='space')entity.color=$('#entityEditColor').value||'#0d3656';else{entity.relation=$('#entityEditRelation').value.trim();entity.city=$('#entityEditCity').value.trim();entity.organization=$('#entityEditOrganization').value.trim();entity.note=$('#entityEditNote').value.trim()}$('#entityEditModal').close();save();toast(kind==='space'?'تم تعديل المساحة':'تم تعديل بيانات الشخص')};
 $$('#entityDeleteForm input[name="entityDeleteAction"]').forEach(input=>input.onchange=()=>{$('#entityMoveField').hidden=input.value!=='move'});
 $('#entityDeleteForm').onsubmit=e=>{e.preventDefault();const kind=$('#entityDeleteKind').value,idValue=$('#entityDeleteId').value,entity=getEntity(kind,idValue);if(!entity)return;const action=$('#entityDeleteForm input[name="entityDeleteAction"]:checked')?.value||'unlink',field=entityField(kind),affected=linkedTasks(kind,idValue);if(action==='move'){const target=$('#entityMoveTarget').value;if(!target)return;data.tasks=data.tasks.map(task=>String(task[field]||'')===String(idValue)?{...task,[field]:target}:task)}else if(action==='delete')deleteTasksWithCredits(affected.map(task=>task.id));else data.tasks=data.tasks.map(task=>String(task[field]||'')===String(idValue)?{...task,[field]:''}:task);if(kind==='space')data.spaces=data.spaces.filter(item=>String(item.id)!==String(idValue));else data.people=data.people.filter(item=>String(item.id)!==String(idValue));$('#entityDeleteModal').close();currentEntity=null;save();showView(kind==='space'?'spaces':'people');toast(kind==='space'?'تم حذف المساحة':'تم حذف الشخص')};
 $('#profileForm').onsubmit=e=>{e.preventDefault();data.profile={name:$('#profileName').value.trim(),email:$('#profileEmail').value.trim()};save();toast('تم حفظ بياناتك');showView('today')};
 $('#manageExportBtn').onclick=()=>$('#exportBtn').click();
 $('#manageImportInput').onchange=async e=>{try{data=migratePoints({...seed,...JSON.parse(await e.target.files[0].text())});save();toast('تمت الاستعادة')}catch{toast('ملف غير صالح')}};
 $('#themeBtn').onclick=()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;localStorage.setItem('mesraah_theme',next)};document.documentElement.dataset.theme=localStorage.getItem('mesraah_theme')||'light';$('#mobileMenu').onclick=()=>document.body.classList.toggle('sidebar-open');$$('#todayFilters button').forEach(b=>b.onclick=()=>{$$('#todayFilters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;renderToday()});$('#globalSearch').addEventListener('input',e=>{const q=e.target.value.trim();if(!q)return;showView('search');$('#searchTitle').textContent='البحث عن: '+q;$('#searchResults').innerHTML=activeTasks().filter(t=>t.title.includes(q)).map(taskHTML).join('')||'<div class="empty-state"><h3>ما لقيت نتيجة</h3></div>'});
 $('#exportBtn').onclick=()=>{const b=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='mesraah-backup.json';a.click();URL.revokeObjectURL(a.href)};$('#importInput').onchange=async e=>{try{data=migratePoints({...seed,...JSON.parse(await e.target.files[0].text())});save();toast('تمت الاستعادة')}catch{toast('ملف غير صالح')}};
 window.MesraahCore={replaceTasks,toast};
 const d=new Date();$('#todayDate').textContent=d.toLocaleDateString('ar-SA',{weekday:'long',day:'numeric',month:'long'});
 installEnhancements();initFly();renderAll();
 showView('today');
})();
